### PR TITLE
Minor update on iiwa14 urdf file

### PR DESCRIPTION
**Pull request by YeZhao**
Some comment update in the iiwa14_tuned_params.urdf

### CODE REVIEW

**Comment by pvarin** [comment]
Do you mean to merge this into kuka-dev?

This looks like it also has a lot of unrelated changes the the build system? Was the kuka_director_planning branch up-to-date with the recent merge from RobotLocomotion?

**Comment by YeZhao** [comment]
I will merge another branch to kuka-dev master soon. The kuka_director_planning branch synchronizes the merge from RobotLocomotion until the end of November 22nd.
https://github.com/HarvardAgileRoboticsLab/drake/commits/kuka_director_planning
For the build changes, which parts do you specifically mean? And should some actions be taken to avoid them?

**Comment by pvarin** [comment]
Oh, I see. The commits go all the way back to Scott's first commit to kuka-dev.

Master is already up-to-date as of two days ago.

You should merge this into the kuka-dev branch which is where we want to do all of the development for the kuka arm.

**Comment by YeZhao** [comment]
Got it. Thanks. Let me fix this issue.

**Pull request closed without merging**
